# build.yml
# GitHub Actions workflow that builds the Tic-Tac-Toe project on Linux,
# Windows, and macOS using a matrix strategy to ensure cross-platform
# compatibility.name: Build C++ Project

name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      # Linux
      - name: Upload executable (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: tictactoe-ubuntu-latest
          path: build/tictactoe

      # macOS
      - name: Upload executable (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: tictactoe-macos-latest
          path: build/tictactoe

      # Windows
      - name: Upload executable (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: tictactoe-windows-latest
          path: build/Release/tictactoe.exe
